bundler_args: --without development
language: ruby
cache: bundler
rvm:
  - jruby
  - rbx
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
matrix:
  allow_failures:
    - rvm:
      - rbx
      - jruby
env:
  - OCTOKIT_TEST_GITHUB_LOGIN="api-padawan" OCTOKIT_TEST_GITHUB_PASSWORD="MYSOCRATESNOTE" OCTOKIT_TEST_GITHUB_TOKEN="6a21f190e3422bf89afa8b360d923b0c30e8fbfa" OCTOKIT_TEST_GITHUB_CLIENT_ID='abcdefabcdefabcdefab' OCTOKIT_TEST_GITHUB_CLIENT_SECRET='abcdefabcdefabcdefababcdefabcdefabcdefab'
before_install:
  - gem update bundler
  - bundle --version
  - gem update --system 2.1.11
  - gem --version
before_script:
  - chmod 600 spec/fixtures/.netrc
