language: ruby

rvm:
  - jruby-19mode
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"

bundler_args: --without development

sudo: false

env:
  global:
    - OCTOKIT_TEST_GITHUB_LOGIN="api-padawan"
    - OCTOKIT_TEST_GITHUB_PASSWORD="MYSOCRATESNOTE"
    - OCTOKIT_TEST_GITHUB_TOKEN="6a21f190e3422bf89afa8b360d923b0c30e8fbfa"
    - OCTOKIT_TEST_GITHUB_CLIENT_ID='abcdefabcdefabcdefab'
    - OCTOKIT_TEST_GITHUB_CLIENT_SECRET='abcdefabcdefabcdefababcdefabcdefabcdefab'
    - OCTOKIT_SILENT=true

before_install:
  - gem update bundler

before_script:
  - chmod 600 spec/fixtures/.netrc

notifications:
  email: false
