bundler_args: --without development
language: ruby
rvm:
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: rbx-18mode
    - rvm: rbx-19mode
env:
  - OCTOKIT_TEST_GITHUB_LOGIN="api-padawan" OCTOKIT_TEST_GITHUB_PASSWORD="MYSOCRATESNOTE" OCTOKIT_TEST_GITHUB_TOKEN="6a21f190e3422bf89afa8b360d923b0c30e8fbfa"
# before_script:
#   - chmod 600 spec/fixtures/.netrc
