name: CI

on:
   push:
     branches:
     - main
     - '*'
     # TODO: Remove references to deprecated `master` and `4-stable` branches
     # once we have tidied up the branch names
     - master
     - 4-stable
   pull_request:
     branches:
     - main
     # TODO: Remove references to deprecated `master` and `4-stable` branches
     # once we have tidied up the branch names
     - master
     - 4-stable

jobs:
  ci:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu ]
        ruby: [ 2.3, 2.4, 2.5, 2.6, 2.7, '3.0', '3.1', head ]
        faraday: [ '~> 1.0', '~> 2.0' ]
        exclude:
          # Faraday 2.x only works with Ruby versions 2.6 onwards.
          # Fortunately, the gem supports Faraday 1.x, so we can just
          # test against that.
          - ruby: 2.5
            faraday: '~> 2.0'
          - ruby: 2.4
            faraday: '~> 2.0'
          - ruby: 2.3
            faraday: '~> 2.0'
    env:
      FARADAY_VERSION: ${{ matrix.faraday }}

    steps:
      - uses: actions/checkout@v2
      - name: Cache Ruby dependencies
        uses: actions/cache@v1
        with:
          path: ./.bundle/gems
          key: cache-${{ runner.os }}-${{ matrix.ruby }}-${{ matrix.faraday }}-${{ github.sha }}
          restore-keys: |
            cache-${{ runner.os }}-${{ matrix.ruby }}-${{ matrix.faraday }}-
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup .netrc
        run: chmod 600 spec/fixtures/.netrc
      - name: Ruby 2.5 and earlier need a newer RubyGems to support frozen-string-literal
        if: ${{ matrix.ruby == '2.5' || matrix.ruby == '2.4' || matrix.ruby == '2.3'  }}
        run: gem update --system 2.7.11
      - name: Install dependencies
        run: |
          bundle config set path .bundle/gems
          bundle config set without development
          bundle install --jobs 4 --retry 3
      - name: Test with RSpec with frozen string literals enabled
        env:
          GITHUB_CI: 1
          RUBYOPT: --enable-frozen-string-literal
        run: bundle exec rspec -w
        if: ${{ matrix.ruby != '2.3' }}
      - name: Test with RSpec without frozen string literals enabled
        env:
          GITHUB_CI: 1
        run: bundle exec rspec -w
        if: ${{ matrix.ruby == '2.3' }}
      - name: Lint with Rubocop
        env:
          GITHUB_CI: 1
        run: bundle exec rubocop
