name: CI
"on":
  push:
    branches:
      - main
      - "*"
  pull_request:
    branches:
      - main
jobs:
  ci:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - head
        faraday:
          - ~> 1.0
          - ~> 2.0
    env:
      FARADAY_VERSION: ${{ matrix.faraday }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache Ruby dependencies
        uses: actions/cache@v4
        with:
          path: ./.bundle/gems
          key: >-
            cache-${{ runner.os }}-${{ matrix.ruby }}-${{ matrix.faraday }}-${{
            github.sha }}
          restore-keys: |
            cache-${{ runner.os }}-${{ matrix.ruby }}-${{ matrix.faraday }}-
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup .netrc
        run: chmod 600 spec/fixtures/.netrc
      - name: Install dependencies
        run: |
          bundle config set path .bundle/gems
          bundle config set without development
          bundle install --jobs 4 --retry 3
      - name: Test with RSpec with frozen string literals enabled
        env:
          GITHUB_CI: 1
          RUBYOPT: "--enable-frozen-string-literal"
        run: bundle exec rspec-queue -w
      - name: Lint with Rubocop
        env:
          GITHUB_CI: 1
        run: bundle exec rubocop
