name: Octokit CI

on: [push]

jobs:
  test:
    name: Ruby version ${{ matrix.ruby_version }}
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      matrix:
        ruby_version: [2.4.x, 2.5.x, 2.6.x]

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby ${{ matrix.ruby_version }}
      uses: actions/setup-ruby@v1
      with:
        version: ${{ matrix.ruby_version }}
    - name: Setup .netrc
      run: |
        chmod 600 spec/fixtures/.netrc
    - name: Install dependencies
      run: |
        gem install bundler
        gem update bundler
        bundle install --without development --jobs 4 --retry 3
    - name: Test with RSpec
      run: |
        bundle exec rake
